# Label PRs automatically based on changed file paths.
# https://github.com/actions/labeler

dashboard:
  - changed-files:
    - any-glob-to-any-file: ["dashboard/**"]

scripts:
  - changed-files:
    - any-glob-to-any-file: ["scripts/**"]

powerbi:
  - changed-files:
    - any-glob-to-any-file: ["PowerBI/**"]

ci:
  - changed-files:
    - any-glob-to-any-file: [".github/**"]

data:
  - changed-files:
    - any-glob-to-any-file: ["dashboard/data.js", "PowerBI/SeedData/**"]
