table Dim_Category

	column Category_ID
		dataType: string
		summarizeBy: none
		sourceColumn: Category_ID
		isKey

	column Category_Name
		dataType: string
		summarizeBy: none
		sourceColumn: Category_Name

	column Sub_Category
		dataType: string
		summarizeBy: none
		sourceColumn: Sub_Category

	partition Dim_Category = m
		mode: import
		source = ```
			let
			    Combined = Table.Combine({Table.RenameColumns(Table.SelectColumns(qFact_PrimarySales, {"Category"}), {{"Category", "Category_ID"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_OfftakeSales, {"Category"}), {{"Category", "Category_ID"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_TDP, {"Category"}), {{"Category", "Category_ID"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_PrimaryArticle, {"Category"}), {{"Category", "Category_ID"}})}),
			    Valid = Table.SelectRows(Combined, each Record.Field(_, "Category_ID") <> null),
			    Unique = fnDimension(Valid, "Category_ID"),
			    Labels = Table.AddColumn(Unique, "Category_Name", each [Category_ID], type text),
			    Final = Table.AddColumn(Labels, "Sub_Category", each null, type text)
			in Table.Distinct(Final, {"Category_ID"})
			```
