table Dim_Date
	lineageTag: c21a8f90-84c1-4f10-9112-a1b2c3d4e001

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d1a2b3c4-0001-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: Date
		isKey

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: d1a2b3c4-0001-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: YearMonth

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d1a2b3c4-0001-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: Year

	column MonthName
		dataType: string
		lineageTag: d1a2b3c4-0001-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: MonthName

	partition Dim_Date = m
		mode: import
		source = ```
			let
			    Source = Csv.Document(File.Contents("\\data-server\MT\Primary\Dim_Date.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"YearMonth", Int64.Type}, {"Year", Int64.Type}, {"MonthName", type text}})
			in
			    #"Changed Type"
			```
