table Dim_Chain

	column Chain_ID
		dataType: string
		summarizeBy: none
		sourceColumn: Chain_ID
		isKey

	column Chain_Name
		dataType: string
		summarizeBy: none
		sourceColumn: Chain_Name

	column Channel_Tier
		dataType: string
		summarizeBy: none
		sourceColumn: Channel_Tier

	partition Dim_Chain = m
		mode: import
		source = ```
			let
			    Combined = Table.Combine({Table.RenameColumns(Table.SelectColumns(qFact_PrimarySales, {"Chain"}), {{"Chain", "Chain_ID"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_OfftakeSales, {"Chain"}), {{"Chain", "Chain_ID"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_TDP, {"Chain"}), {{"Chain", "Chain_ID"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_PrimaryArticle, {"Chain"}), {{"Chain", "Chain_ID"}})}),
			    Valid = Table.SelectRows(Combined, each Record.Field(_, "Chain_ID") <> null),
			    Unique = fnDimension(Valid, "Chain_ID"),
			    Labels = Table.AddColumn(Unique, "Chain_Name", each [Chain_ID], type text),
			    Final = Table.AddColumn(Labels, "Channel_Tier", each null, type text)
			in Table.Distinct(Final, {"Chain_ID"})
			```
