table Dim_Category

	column Category_ID
		dataType: string
		summarizeBy: none
		sourceColumn: Category_ID
		isKey

	column Category_Name
		dataType: string
		summarizeBy: none
		sourceColumn: Category_Name

	column Sub_Category
		dataType: string
		summarizeBy: none
		sourceColumn: Sub_Category

	partition Dim_Category = m
		mode: import
		source = ```
			let
			    Combined = Table.Combine({Table.RenameColumns(Table.SelectColumns(qFact_PrimarySales, {"Category Key", "Category"}), {{"Category Key", "Category_ID"}, {"Category", "Category_Name"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_OfftakeSales, {"Category Key", "Category"}), {{"Category Key", "Category_ID"}, {"Category", "Category_Name"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_TDP, {"Category Key", "Category"}), {{"Category Key", "Category_ID"}, {"Category", "Category_Name"}}),
			        Table.RenameColumns(Table.SelectColumns(qFact_PrimaryArticle, {"Category Key", "Category"}), {{"Category Key", "Category_ID"}, {"Category", "Category_Name"}})}),
			    Valid = Table.SelectRows(Combined, each Record.Field(_, "Category_ID") <> null),
			    Unique = fnDimension(Valid, "Category_ID"),
			    Final = Table.AddColumn(Unique, "Sub_Category", each null, type text)
			in Table.Distinct(Final, {"Category_ID"})
			```
