const assert=require('assert'); const {launchChromium}=require('./browser_launch');
(async()=>{const b=await launchChromium();try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:${process.env.SWEEP_PORT||8899}/index.html`);await p.waitForFunction(()=>typeof F!=='undefined');
const results=await p.evaluate(()=>{
 const row=(month,brand,nsv,claim,extra={})=>({schema_version:2,record_type:'SALES',fy:'FY27',month,chain:'Apollo',brand,channel:'MT',nsv,tax:nsv*.05,mrp:2*nsv,claim_amount:claim,ba_amount:null,covered_nsv:claim===null?0:nsv,status:'NOT_AVAILABLE',cm2_value:null,cm2_pct:null,source_status:'PROVISION',gst_qc_status:'VALID_5_PERCENT',gst_review_count:0,gst_missing_tax_count:0,reviewed_amount:0,reviewed_nsv:0,reviewed_tax:0,missing_tax_nsv:0,allocation_basis:'NSV_SHARE_ESTIMATE',cogs_basis_status:'UNRESOLVED',approval_status:'PENDING_FINANCE',assumption_version:'fixture',source_version:'fixture',timing_status:'NOT_CERTIFIED',...extra});
 const apr=[row('2026-04','A',60,6,{ba_amount:3}),row('2026-04','B',40,4,{ba_amount:2})];
 D.cm2.views={contract_version:2,channel_basis:'MT',assumptions:{cogs_basis_status:'UNRESOLVED',rates_applied:false},provision:{source_available:true,rows:[...apr,row('2026-08','A',80,8),{...row('2026-04','A',900,90),chain:'Other'}],exception_rows:[{fy:'FY27',month:'2026-04',chain:'Apollo',record_type:'UNALLOCATED_BA',ba_amount:-3,status:'UNALLOCATED_NO_SALES',source_status:'PROVISION'}]},recorded_dn:{source_available:true,rows:[...apr.map(r=>({...r,claim_amount:r.claim_amount*2,ba_amount:null,source_status:'RECORDED_DN'})),row('2026-08','A',80,12,{source_status:'PARTIAL_REGISTER',gst_qc_status:'REVIEW_RATE_OR_BASE',gst_review_count:1,reviewed_amount:80,reviewed_nsv:80,reviewed_tax:4}),row('2026-05','A',-10,null)],exception_rows:[]},matched_bridge:{keys:[['2026-04','Apollo'],['2026-08','Apollo']],status:'NOT_COMPARABLE'}};
 Object.keys(F).forEach(k=>F[k]=[]);F.FY=['FY27'];F.Month=['April'];F.Chain=['Apollo'];
 const snap=()=>{buildPnl();const el=document.getElementById('cm2Views');if(!el)return {missing:true};const captured={},csv=downloadRowsCSV,xlsx=downloadRowsXLSX;downloadRowsCSV=r=>captured.csv=r;downloadRowsXLSX=r=>captured.xlsx=r;el.querySelector('[data-cm2-export="csv"]').click();el.querySelector('[data-cm2-export="xlsx"]').click();const ownCsv=captured.csv;exportChart('cm2SourceChart','csv');captured.chartCsv=captured.csv;captured.csv=ownCsv;downloadRowsCSV=csv;downloadRowsXLSX=xlsx;return {text:el.textContent,csv:captured.csv,xlsx:captured.xlsx,table:tableToRows(el.querySelector('table')),chartCsv:captured.chartCsv,tooltip:charts.filter(c=>c.canvas&&c.canvas.id==='cm2SourceChart'&&document.body.contains(c.canvas)).map(c=>c.options.plugins.tooltip.callbacks.label({dataset:c.data.datasets[1],raw:c.data.datasets[1].data[0],label:c.data.labels[0]})),chart:charts.filter(c=>c.canvas&&c.canvas.id==='cm2SourceChart'&&document.body.contains(c.canvas)).map(c=>c.data.datasets.map(d=>d.data))};};
 const april=snap();F.Chain=[];const unmatched=snap();F.Chain=['Apollo'];F.Month=['May'];const missing=snap();F.Month=['Aug'];const august=snap();F.Category=['Skin'];const category=snap();F.Category=[];F.Month=['April'];F.Brand=['A'];const brand=snap();F.Brand=[];F.FY=['FY99'];const absent=snap();return {april,missing,august,category,brand,absent,unmatched};});
const fixes=[['matched bridge chart excludes unmatched source keys',()=>assert.deepStrictEqual(results.unmatched.chart[0],[[10],[20]])],['export rows align to fact headers',()=>{assert(results.april.csv.every(r=>r.length===results.april.csv[0].length));const header=results.april.csv[0],bridge=results.april.csv.find(r=>r[header.indexOf('record_type')]==='MATCHED_BRIDGE');assert(bridge);assert.strictEqual(bridge[header.indexOf('matched_nsv')],100);assert.strictEqual(bridge[header.indexOf('provision_claims')],10);assert.strictEqual(bridge[header.indexOf('recorded_dn_claims')],20);assert.strictEqual(bridge[header.indexOf('claim_difference')],10);}],['absent FY amounts unavailable',()=>assert(!results.absent.text.includes('₹0.00 L'))]];let fixFailures=0;for(const [name,check] of fixes){try{check();console.log('PASS '+name);}catch(e){fixFailures++;console.error('FAIL '+name+': '+e.message);}}assert.strictEqual(fixFailures,0,'review fixes');
assert(!results.april.missing,'governed CM2 views must render');assert(results.april.text.includes('100.00')&&results.april.text.includes('10.00')&&results.april.text.includes('20.00'),'April Apollo monetary selection');assert(results.april.csv.some(r=>r.includes('UNALLOCATED_BA')&&r.includes(-3)),'signed BA exception exported');assert.deepStrictEqual(results.april.csv,results.april.xlsx,'CSV/XLSX parity');assert(!JSON.stringify(results.april.csv).includes('Other'),'no out-of-scope export');assert.deepStrictEqual(results.april.chart[0],[[10],[20]],'alternative claim chart population');assert(results.april.text.includes('Matched claim bridge'),'matched bridge');assert(results.august.tooltip[0].includes('PARTIAL_REGISTER'),'tooltip carries partial source status');assert.deepStrictEqual(results.april.chartCsv,results.april.csv,'chart CSV carries same source status/scope');assert(results.april.table[1][4]==='₹60.00 L'&&results.april.table[2][4]==='₹40.00 L','table selected signed sales population');assert(results.august.text.includes('PARTIAL_REGISTER')&&results.august.text.includes('80.00'),'partial and reviewed exposure');assert(results.category.text.includes('UNSUPPORTED_SCOPE'),'category withheld');assert(results.brand.text.includes('NSV-share allocated estimate')&&results.brand.text.includes('60.00'),'brand allocation and scope');assert(results.absent.text.includes('No source rows')&&!results.absent.text.includes('100.00'),'no stale FY fallback');assert.deepStrictEqual(results.missing.chart,[],'unmatched month has no matched bridge chart');assert.deepStrictEqual(errors,[]);console.log('PASS CM2 views scope, partial/GST status, signed exception, bridge, chart, exports and missing claims');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
