"""Entry point for the Honasa MT data-engineering skills.

    python3 -m scripts.dataeng.cli <skill> [--json]

Skills: scan | registry | lineage | validate | quality | reconcile |
        governance | health | all

`health` runs every engine, writes all reports to outputs/dataeng/ and prints a
Production Readiness Score. Exit code is 0 for PASS/INFO/WARN, 1 for FAIL or
BLOCKED, so it can gate CI.
"""
from __future__ import annotations

import argparse
import json
import sys

from . import governance, quality, reconcile, registry, repo_scan, validate
from .core import Finding, OUT_DIR, git, rel, write_csv, write_json

FINDING_COLS = ["id", "skill", "category", "severity", "summary", "evidence",
                "amount_l", "location", "owner", "decision_ref", "remediation"]

# Score weights: what actually stops a release weighs most.
SEVERITY_PENALTY = {"BLOCKED": 12, "FAIL": 8, "WARN": 2, "INFO": 0, "PASS": 0}


def _print(findings: list[Finding], title: str) -> None:
    order = {"BLOCKED": 0, "FAIL": 1, "WARN": 2, "INFO": 3, "PASS": 4}
    print(f"\n=== {title} ===")
    for f in sorted(findings, key=lambda x: order[x.severity]):
        amt = f" [{f.amount_l} L]" if f.amount_l else ""
        print(f"  {f.severity:<7} {f.id:<38} {f.summary}{amt}")
        if f.evidence and f.severity in ("BLOCKED", "FAIL", "WARN"):
            print(f"          evidence: {f.evidence}")


def readiness(findings: list[Finding]) -> tuple[int, str]:
    penalty = sum(SEVERITY_PENALTY[f.severity] for f in findings)
    score = max(0, 100 - penalty)
    if any(f.severity == "BLOCKED" for f in findings):
        verdict = "NOT READY — blocked"
    elif any(f.severity == "FAIL" for f in findings):
        verdict = "NOT READY — failing checks"
    elif any(f.severity == "WARN" for f in findings):
        verdict = "READY WITH ACCEPTED EXCEPTIONS — every WARN needs a named owner"
    else:
        verdict = "READY"
    return score, verdict


def run_all(write: bool = True) -> tuple[list[Finding], dict]:
    all_f: list[Finding] = []
    artifacts: dict[str, str] = {}

    inventory, edges, f_scan = repo_scan.scan()
    all_f += f_scan
    metrics, f_reg = registry.build()
    all_f += f_reg
    f_val = validate.run()
    all_f += f_val
    f_dq = quality.run()
    all_f += f_dq
    f_rec = reconcile.run()
    all_f += f_rec
    decisions, f_gov = governance.run()
    all_f += f_gov

    if write:
        artifacts["repository_knowledge_graph"] = rel(write_csv("repository_inventory.csv", inventory))
        artifacts["dependency_edges"] = rel(write_csv("dependency_edges.csv", edges))
        artifacts["metric_registry"] = rel(write_csv("metric_registry.csv", metrics))
        artifacts["data_lineage_map"] = rel(write_csv("data_lineage_map.csv", registry.lineage_rows()))
        artifacts["decision_register_view"] = rel(write_csv("decision_register_view.csv", decisions))
        artifacts["findings"] = rel(write_csv(
            "findings.csv", [f.as_dict() for f in all_f], FINDING_COLS))
        by_skill: dict[str, dict[str, int]] = {}
        for f in all_f:
            by_skill.setdefault(f.skill, {}).setdefault(f.severity, 0)
            by_skill[f.skill][f.severity] += 1
        score, verdict = readiness(all_f)
        artifacts["health_report"] = rel(write_json("health_report.json", {
            "generated_from_commit": git("rev-parse", "HEAD"),
            "production_readiness_score": score,
            "verdict": verdict,
            "counts_by_skill": by_skill,
            "counts_by_severity": {s: sum(1 for f in all_f if f.severity == s)
                                   for s in ("BLOCKED", "FAIL", "WARN", "INFO", "PASS")},
            "artifacts": artifacts,
            "note": ("Generated by scripts/dataeng. Regenerate after any build; "
                     "these reports are derived, never hand-edited."),
        }))
    return all_f, artifacts


SKILLS = {
    "scan": lambda: repo_scan.scan()[2],
    "registry": lambda: registry.build()[1],
    "lineage": lambda: registry.build()[1],
    "validate": validate.run,
    "quality": quality.run,
    "reconcile": reconcile.run,
    "governance": lambda: governance.run()[1],
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("skill", choices=[*SKILLS, "health", "all"])
    ap.add_argument("--json", action="store_true", help="emit findings as JSON")
    a = ap.parse_args(argv)

    if a.skill in ("health", "all"):
        findings, artifacts = run_all(write=True)
        if a.json:
            print(json.dumps([f.as_dict() for f in findings], indent=2))
        else:
            for skill in sorted({f.skill for f in findings}):
                _print([f for f in findings if f.skill == skill], skill)
            score, verdict = readiness(findings)
            print("\n" + "=" * 72)
            counts = {s: sum(1 for f in findings if f.severity == s)
                      for s in ("BLOCKED", "FAIL", "WARN", "INFO", "PASS")}
            print(f"  BLOCKED {counts['BLOCKED']}   FAIL {counts['FAIL']}   "
                  f"WARN {counts['WARN']}   INFO {counts['INFO']}   PASS {counts['PASS']}")
            print(f"  PRODUCTION READINESS SCORE: {score}/100")
            print(f"  VERDICT: {verdict}")
            print("=" * 72)
            print(f"\nReports written to {rel(OUT_DIR)}/:")
            for k, v in artifacts.items():
                print(f"  {k:32} {v}")
    else:
        findings = SKILLS[a.skill]()
        if a.json:
            print(json.dumps([f.as_dict() for f in findings], indent=2))
        else:
            _print(findings, a.skill)

    return 1 if any(f.severity in ("FAIL", "BLOCKED") for f in findings) else 0


if __name__ == "__main__":
    sys.exit(main())
