"""Entry point for the Honasa MT data-engineering skills.

    python3 -m scripts.dataeng.cli <skill> [--json]
    python3 -m scripts.dataeng.cli health --save-baseline
    python3 -m scripts.dataeng.cli health --regression

Skills: scan | registry | lineage | validate | quality | reconcile |
        governance | health | all

`health` runs every engine, writes all reports to outputs/dataeng/ and prints a
Production Readiness Score. Exit code is 0 for PASS/INFO/WARN, 1 for FAIL or
BLOCKED, so it can gate CI.

`--save-baseline`  write current non-PASS findings to config/dataeng_baseline.json.
`--regression`     exit 1 only on findings that are NEW (not in the baseline) and
                   are FAIL or BLOCKED; pre-existing accepted WARNs do not block CI.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

from . import governance, quality, reconcile, registry, repo_scan, seed_manager, validate
from .core import Finding, OUT_DIR, ROOT, git, rel, write_csv, write_json

BASELINE_PATH = ROOT / "config" / "dataeng_baseline.json"

FINDING_COLS = ["id", "skill", "category", "severity", "summary", "evidence",
                "amount_l", "location", "owner", "decision_ref", "remediation"]

# Score weights: what actually stops a release weighs most.
SEVERITY_PENALTY = {"BLOCKED": 12, "FAIL": 8, "WARN": 2, "INFO": 0, "PASS": 0}


def _print(findings: list[Finding], title: str) -> None:
    order = {"BLOCKED": 0, "FAIL": 1, "WARN": 2, "INFO": 3, "PASS": 4}
    print(f"\n=== {title} ===")
    for f in sorted(findings, key=lambda x: order[x.severity]):
        amt = f" [{f.amount_l} L]" if f.amount_l else ""
        print(f"  {f.severity:<7} {f.id:<38} {f.summary}{amt}")
        if f.evidence and f.severity in ("BLOCKED", "FAIL", "WARN"):
            print(f"          evidence: {f.evidence}")


def readiness(findings: list[Finding]) -> tuple[int, str]:
    penalty = sum(SEVERITY_PENALTY[f.severity] for f in findings)
    score = max(0, 100 - penalty)
    if any(f.severity == "BLOCKED" for f in findings):
        verdict = "NOT READY — blocked"
    elif any(f.severity == "FAIL" for f in findings):
        verdict = "NOT READY — failing checks"
    elif any(f.severity == "WARN" for f in findings):
        verdict = "READY WITH ACCEPTED EXCEPTIONS — every WARN needs a named owner"
    else:
        verdict = "READY"
    return score, verdict


def run_all(write: bool = True) -> tuple[list[Finding], dict]:
    all_f: list[Finding] = []
    artifacts: dict[str, str] = {}

    inventory, edges, f_scan = repo_scan.scan()
    all_f += f_scan
    metrics, f_reg = registry.build()
    all_f += f_reg
    f_val = validate.run()
    all_f += f_val
    f_dq = quality.run()
    all_f += f_dq
    f_rec = reconcile.run()
    all_f += f_rec
    decisions, f_gov = governance.run()
    all_f += f_gov

    if write:
        artifacts["repository_knowledge_graph"] = rel(write_csv("repository_inventory.csv", inventory))
        artifacts["dependency_edges"] = rel(write_csv("dependency_edges.csv", edges))
        artifacts["metric_registry"] = rel(write_csv("metric_registry.csv", metrics))
        artifacts["data_lineage_map"] = rel(write_csv("data_lineage_map.csv", registry.lineage_rows()))
        artifacts["decision_register_view"] = rel(write_csv("decision_register_view.csv", decisions))
        artifacts["findings"] = rel(write_csv(
            "findings.csv", [f.as_dict() for f in all_f], FINDING_COLS))
        by_skill: dict[str, dict[str, int]] = {}
        for f in all_f:
            by_skill.setdefault(f.skill, {}).setdefault(f.severity, 0)
            by_skill[f.skill][f.severity] += 1
        score, verdict = readiness(all_f)
        artifacts["health_report"] = rel(write_json("health_report.json", {
            "generated_from_commit": git("rev-parse", "HEAD"),
            "production_readiness_score": score,
            "verdict": verdict,
            "counts_by_skill": by_skill,
            "counts_by_severity": {s: sum(1 for f in all_f if f.severity == s)
                                   for s in ("BLOCKED", "FAIL", "WARN", "INFO", "PASS")},
            "artifacts": artifacts,
            "note": ("Generated by scripts/dataeng. Regenerate after any build; "
                     "these reports are derived, never hand-edited."),
        }))
    return all_f, artifacts


SKILLS = {
    "scan": lambda: repo_scan.scan()[2],
    "registry": lambda: registry.build()[1],
    "lineage": lambda: registry.build()[1],
    "validate": validate.run,
    "quality": quality.run,
    "reconcile": reconcile.run,
    "governance": lambda: governance.run()[1],
    "seed": seed_manager.validate,
}


def _load_baseline() -> dict:
    if BASELINE_PATH.exists():
        return json.loads(BASELINE_PATH.read_text(encoding="utf-8")).get("accepted", {})
    return {}


def _save_baseline(findings: list[Finding]) -> None:
    accepted = {
        f.id: {"severity": f.severity, "summary": f.summary[:120],
               "owner": f.owner or "", "decision_ref": f.decision_ref or ""}
        for f in findings if f.severity != "PASS"
    }
    payload = {
        "version": 1,
        "generated_from_commit": git("rev-parse", "HEAD"),
        "generated_at": __import__("datetime").date.today().isoformat(),
        "description": (
            "Machine-readable accepted-findings baseline. "
            "Regenerate: python3 -m scripts.dataeng.cli health --save-baseline"
        ),
        "accepted": accepted,
    }
    BASELINE_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Baseline written → {rel(BASELINE_PATH)}  ({len(accepted)} accepted findings)")


def _regression_exit(findings: list[Finding]) -> int:
    """Return 1 only for NEW FAIL/BLOCKED findings not already in the baseline."""
    baseline = _load_baseline()
    new_critical = [
        f for f in findings
        if f.severity in ("FAIL", "BLOCKED") and f.id not in baseline
    ]
    if new_critical:
        print("\n=== REGRESSION: NEW CRITICAL FINDINGS ===")
        for f in new_critical:
            print(f"  {f.severity:<7} {f.id:<38} {f.summary}")
        return 1
    # All FAIL/BLOCKED are pre-existing; WARNs accepted.
    pre_existing = [f for f in findings if f.severity in ("FAIL", "BLOCKED")]
    if pre_existing:
        print(f"\nRegression mode: {len(pre_existing)} pre-existing FAIL/BLOCKED in baseline — not blocking CI.")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("skill", choices=[*SKILLS, "health", "all",
                                       "seed-list", "seed-resolve", "seed-verify-hash"])
    ap.add_argument("--json", action="store_true", help="emit findings as JSON")
    ap.add_argument("--save-baseline", action="store_true",
                    help="save current non-PASS findings as the accepted baseline")
    ap.add_argument("--regression", action="store_true",
                    help="CI mode: exit 1 only on NEW FAIL/BLOCKED not in baseline")
    ap.add_argument("args", nargs="*", help="extra arguments for seed-resolve / seed-verify-hash")
    a = ap.parse_args(argv)

    if a.skill in ("health", "all"):
        findings, artifacts = run_all(write=True)
        if a.json:
            print(json.dumps([f.as_dict() for f in findings], indent=2))
        else:
            for skill in sorted({f.skill for f in findings}):
                _print([f for f in findings if f.skill == skill], skill)
            score, verdict = readiness(findings)
            print("\n" + "=" * 72)
            counts = {s: sum(1 for f in findings if f.severity == s)
                      for s in ("BLOCKED", "FAIL", "WARN", "INFO", "PASS")}
            print(f"  BLOCKED {counts['BLOCKED']}   FAIL {counts['FAIL']}   "
                  f"WARN {counts['WARN']}   INFO {counts['INFO']}   PASS {counts['PASS']}")
            print(f"  PRODUCTION READINESS SCORE: {score}/100")
            print(f"  VERDICT: {verdict}")
            print("=" * 72)
            print(f"\nReports written to {rel(OUT_DIR)}/:")
            for k, v in artifacts.items():
                print(f"  {k:32} {v}")
        if a.save_baseline:
            _save_baseline(findings)
    elif a.skill == "seed-list":
        rows = seed_manager.list_seeds()
        if a.json:
            print(json.dumps(rows, indent=2))
        else:
            for r in rows:
                print(f"  {r['Key']:<10} {r['Status']:<15} {r['Value']:<12} "
                      f"ctrl={r['Control']:<10} sha={r['SHA256_prefix']}…  {r['Source_File']}")
        return 0
    elif a.skill == "seed-resolve":
        if len(a.args) < 2:
            print("Usage: seed-resolve <metric> <month>  e.g. seed-resolve GMV Jun-26")
            return 1
        val, status = seed_manager.resolve(a.args[0], a.args[1])
        print(f"  metric={a.args[0]!r}  month={a.args[1]!r}  value={val}  status={status}")
        return 0 if status == "AUTHORITATIVE" else 1
    elif a.skill == "seed-verify-hash":
        if not a.args:
            print("Usage: seed-verify-hash <path-to-source-file>")
            return 1
        sha, matched = seed_manager.verify_hash(a.args[0])
        if matched is None:
            print(f"  SHA256={sha}  (no baseline SHA recorded for this file)")
        elif matched:
            print(f"  SHA256={sha}  MATCH — file is the recorded authoritative source")
        else:
            print(f"  SHA256={sha}  MISMATCH — file differs from the recorded source")
        return 0 if matched is not False else 1
    else:
        findings = SKILLS[a.skill]()
        if a.json:
            print(json.dumps([f.as_dict() for f in findings], indent=2))
        else:
            _print(findings, a.skill)

    if a.regression:
        return _regression_exit(findings)
    return 1 if any(f.severity in ("FAIL", "BLOCKED") for f in findings) else 0


if __name__ == "__main__":
    sys.exit(main())
