#!/usr/bin/env python3
"""
Milestone 2: Pipeline Health Risk Matrix — Chain-wise FY27 Pipeline Ratio Analysis
Produces: exports/Pipeline_Health_Risk_Matrix_<date>.xlsx
"""
import json
from pathlib import Path
from datetime import date

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    import os; os.system("pip install openpyxl -q")
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

# ── Load enriched metrics (generated by generate_enriched_metrics.py) ─────────
em_path = Path('dashboard/enriched_metrics.json')
if not em_path.exists():
    print("enriched_metrics.json not found — run generate_enriched_metrics.py first")
    raise SystemExit(1)
em = json.loads(em_path.read_text())

NAVY  = "10254A"
RED   = "C0392B"
GREEN = "1E8449"
AMBER = "E67E22"
BLUE  = "1A5276"
WHITE = "FFFFFF"
LIGHT = "EAF0FB"
LIGHT_RED   = "FDECEA"
LIGHT_GREEN = "E9F7EF"
LIGHT_AMBER = "FEF9E7"
GRAY  = "95A5A6"

thin = Side(style='thin', color='CCCCCC')
border = Border(left=thin, right=thin, top=thin, bottom=thin)

def hdr(ws, r, ncols, color=NAVY):
    for c in range(1, ncols+1):
        cell = ws.cell(row=r, column=c)
        cell.font = Font(bold=True, color=WHITE, size=10, name='Calibri')
        cell.fill = PatternFill("solid", fgColor=color)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = border

def cs(ws, r, c, val, bold=False, align="left", color=None, bg=None, fmt=None):
    cell = ws.cell(row=r, column=c, value=val)
    cell.font = Font(bold=bold, color=color or "000000", name='Calibri', size=9)
    cell.alignment = Alignment(horizontal=align, vertical="center")
    cell.border = border
    if bg:
        cell.fill = PatternFill("solid", fgColor=bg)
    if fmt:
        cell.number_format = fmt
    return cell

# ── Workbook ──────────────────────────────────────────────────────────────────
wb = Workbook()

# ── Sheet 1: Chain Pipeline Risk Matrix ───────────────────────────────────────
ws = wb.active
ws.title = "Chain Pipeline Risk"
ws.freeze_panes = 'B3'

ws.merge_cells('A1:L1')
tc = ws.cell(row=1, column=1, value=f"Pipeline Health Risk Matrix — FY27 YTD ({em['fy27_period']}) | All Values ₹ Lakh")
tc.font = Font(bold=True, color=WHITE, size=12, name='Calibri')
tc.fill = PatternFill("solid", fgColor=NAVY)
tc.alignment = Alignment(horizontal="center", vertical="center")
ws.row_dimensions[1].height = 28

ws.merge_cells('A2:L2')
sub = ws.cell(row=2, column=1,
    value=f"Pipeline Ratio = Primary NSV ÷ Offtake NSV | High Risk >1.40 🔴 | Healthy 0.75–1.40 🟢 | Stockout <0.75 🟡 | Generated {date.today()}")
sub.font = Font(italic=True, color=GRAY, size=8, name='Calibri')
sub.fill = PatternFill("solid", fgColor="F0F3FA")
sub.alignment = Alignment(horizontal="center")

COLS = ['Chain / RKAM', 'FY26 NSV (₹L)', 'FY26 Offtake', 'FY26 Pipeline', 'FY27 YTD (₹L)',
        'FY27 TGT (₹L)', 'ACH %', 'FY27 Run-Rate', 'FY27 Offtake', 'FY27 Pipeline',
        'Risk Bucket', 'Recommendation']
hdr(ws, 3, len(COLS))
for i, h in enumerate(COLS, 1):
    ws.cell(row=3, column=i).value = h
ws.row_dimensions[3].height = 42

chains = em.get('by_chain', [])
DOCS_NOTE = {
    'high_risk': 'Reduce primary dispatches — channel inventory bloated (DOC >10d). Hold orders & drive secondary sell-through.',
    'healthy': 'Maintain current dispatch cadence. Monitor DOC weekly.',
    'stockout': 'Accelerate primary fill — risk of OSA failure. Expedite dispatch; check DC inventory.',
}

for ri, c in enumerate(chains, 4):
    flag = c.get('pipeline_flag') or 'healthy'
    bg = LIGHT_RED if flag == 'high_risk' else (LIGHT_AMBER if flag == 'stockout' else ('F9F9F9' if ri % 2 == 0 else WHITE))
    fg_pip = RED if flag == 'high_risk' else (AMBER if flag == 'stockout' else GREEN)

    cs(ws, ri, 1, c['name'], bold=(c['name'] not in ('Unmapped Chain', 'Unknown')), bg=bg)
    cs(ws, ri, 2, c['fy26_nsv'], align="right", bg=bg, fmt='#,##0.00')
    cs(ws, ri, 3, c.get('fy26_offtake') or '–', align="right", bg=bg)
    pip26 = c.get('pipeline_ratio_fy26')
    pip26_cell = cs(ws, ri, 4, f"{pip26:.2f}" if pip26 else '–', align="center", bg=bg, bold=True)
    cs(ws, ri, 5, c['fy27_ytd'], align="right", bg=bg, fmt='#,##0.00')
    cs(ws, ri, 6, c['fy27_tgt'], align="right", bg=bg, fmt='#,##0.00')
    ach = c.get('fy27_ach_pct')
    ach_cell = cs(ws, ri, 7, f"{ach}%" if ach is not None else '–', align="center", bg=bg, bold=True)
    if ach is not None:
        ach_col = GREEN if ach >= 100 else (AMBER if ach >= 80 else RED)
        ach_cell.font = Font(bold=True, color=ach_col, name='Calibri', size=9)
    cs(ws, ri, 8, c['fy27_run_rate'], align="right", bg=bg, fmt='#,##0.00')
    cs(ws, ri, 9, c.get('fy27_offtake') or '–', align="right", bg=bg)
    pip27 = c.get('pipeline_ratio_fy27')
    pip27_cell = cs(ws, ri, 10, f"{pip27:.2f}" if pip27 else '–', align="center", bg=bg, bold=True)
    if pip27 is not None:
        pip27_cell.font = Font(bold=True, color=fg_pip, name='Calibri', size=9)
    bucket = {'high_risk': '🔴 HIGH RISK (>1.40)', 'stockout': '🟡 STOCKOUT (<0.75)', 'healthy': '🟢 HEALTHY'}.get(flag, '–')
    cs(ws, ri, 11, bucket, align="center", bg=bg, bold=True)
    cs(ws, ri, 12, DOCS_NOTE.get(flag, ''), bg=bg)

widths = [28, 14, 14, 13, 14, 14, 9, 14, 14, 13, 18, 52]
for i, w in enumerate(widths, 1):
    ws.column_dimensions[get_column_letter(i)].width = w

# ── Sheet 2: Zone Summary ─────────────────────────────────────────────────────
wz = wb.create_sheet("Zone Scorecard")
wz.freeze_panes = 'B3'
wz.merge_cells('A1:I1')
zt = wz.cell(row=1, column=1, value=f"Zone Scorecard — FY27 YTD ({em['fy27_period']})")
zt.font = Font(bold=True, color=WHITE, size=12, name='Calibri')
zt.fill = PatternFill("solid", fgColor=NAVY)
zt.alignment = Alignment(horizontal="center", vertical="center")
wz.row_dimensions[1].height = 28

ZCOLS = ['Zone', 'FY26 NSV (₹L)', 'FY27 YTD (₹L)', 'FY27 TGT (₹L)', 'ACH %', 'Run-Rate', 'Pipeline Ratio', 'Status', 'MoM Trend (FY27)']
hdr(wz, 2, len(ZCOLS))
for i, h in enumerate(ZCOLS, 1):
    wz.cell(row=2, column=i).value = h
wz.row_dimensions[2].height = 36

for ri, z in enumerate(em.get('by_zone', []), 3):
    flag = z.get('pipeline_flag') or 'healthy'
    status_col = {'on_track': GREEN, 'monitor': AMBER, 'escalate': RED}.get(z.get('status', ''), GRAY)
    bg = LIGHT if ri % 2 == 0 else WHITE
    cs(wz, ri, 1, z['name'], bold=True, bg=bg)
    cs(wz, ri, 2, z['fy26_nsv'], align="right", bg=bg, fmt='#,##0.00')
    cs(wz, ri, 3, z['fy27_ytd'], align="right", bg=bg, fmt='#,##0.00')
    cs(wz, ri, 4, z['fy27_tgt'], align="right", bg=bg, fmt='#,##0.00')
    ach = z.get('fy27_ach_pct')
    ac = cs(wz, ri, 5, f"{ach}%" if ach is not None else '–', align="center", bg=bg, bold=True)
    if ach is not None:
        ac.font = Font(bold=True, color=GREEN if ach >= 100 else (AMBER if ach >= 80 else RED), name='Calibri', size=9)
    cs(wz, ri, 6, z['fy27_run_rate'], align="right", bg=bg, fmt='#,##0.00')
    p27 = z.get('pipeline_ratio_fy27')
    pc = cs(wz, ri, 7, f"{p27:.2f}" if p27 else '–', align="center", bg=bg, bold=True)
    if p27:
        pc.font = Font(bold=True, color=RED if p27 > 1.4 else (AMBER if p27 < 0.75 else GREEN), name='Calibri', size=9)
    sc = cs(wz, ri, 8, z.get('status', '–').replace('_', ' ').title(), align="center", bg=bg, bold=True)
    sc.font = Font(bold=True, color=status_col, name='Calibri', size=9)
    monthly = z.get('monthly_fy27', {})
    trend = '  '.join(f"{m[:3]}:₹{v:.1f}L" for m, v in sorted(monthly.items()))
    cs(wz, ri, 9, trend or '–', bg=bg)

for i, w in enumerate([20, 14, 14, 14, 9, 12, 14, 14, 40], 1):
    wz.column_dimensions[get_column_letter(i)].width = w

# ── Sheet 3: Risk Summary Dashboard ───────────────────────────────────────────
wd = wb.create_sheet("Risk Summary")
ph = em.get('pipeline_health', {})
wd.merge_cells('A1:D1')
dt = wd.cell(row=1, column=1, value="Pipeline Health — Risk Bucket Summary")
dt.font = Font(bold=True, color=WHITE, size=13, name='Calibri')
dt.fill = PatternFill("solid", fgColor=NAVY)
dt.alignment = Alignment(horizontal="center", vertical="center")
wd.row_dimensions[1].height = 28

summary = [
    ("🔴 HIGH RISK (Pipeline >1.40)", len(ph.get('high_risk_chains', [])), RED,
     "Channel blockage risk. Reduce primary dispatches; drive secondary sell-through"),
    ("🟢 HEALTHY (0.75–1.40)", len(ph.get('healthy_chains', [])), GREEN,
     "Balanced primary-to-offtake. Maintain dispatch cadence; monitor weekly"),
    ("🟡 STOCKOUT RISK (<0.75)", len(ph.get('stockout_chains', [])), AMBER,
     "Offtake outstripping supply. Expedite dispatch; check DC inventory urgently"),
]
hdr(wd, 2, 4, BLUE)
for i, h in enumerate(['Risk Bucket', '# Chains', 'Action Priority', 'Description'], 1):
    wd.cell(row=2, column=i).value = h
for ri, (label, count, col, desc) in enumerate(summary, 3):
    cs(wd, ri, 1, label, bold=True, color=col)
    cs(wd, ri, 2, count, align="center", bold=True, color=col)
    priority = {'C0392B': '🔴 Immediate', '1E8449': '🟢 Routine', 'E67E22': '🟡 Urgent'}.get(col, '–')
    cs(wd, ri, 3, priority, align="center", bold=True)
    cs(wd, ri, 4, desc)

for i, w in enumerate([32, 10, 16, 60], 1):
    wd.column_dimensions[get_column_letter(i)].width = w

# ── Save ──────────────────────────────────────────────────────────────────────
Path('exports').mkdir(exist_ok=True)
out = f"exports/Pipeline_Health_Risk_Matrix_{date.today().strftime('%Y%m%d')}.xlsx"
wb.save(out)

hr = ph.get('high_risk_chains', [])
print(f"✅ Pipeline health Excel saved: {out}")
print(f"   🔴 High Risk ({len(hr)}): {[c['name'] for c in hr[:5]]}")
print(f"   🟢 Healthy:   {len(ph.get('healthy_chains', []))}")
print(f"   🟡 Stockout:  {len(ph.get('stockout_chains', []))}")
